org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.20.1
loader_version=0.16.10
fabric_version=0.92.2+1.20.1
fabric_kotlin_version=1.13.7+kotlin.2.2.21

mod_version=1.0.3
maven_group=com.bluup.hexwright
archives_base_name=hexwright
hexcasting_version=0.11.4
moreiotas_version=0.1.2
ldlib_version=1.0.50
jei_version=15.21.0.148
emi_version=1.1.24+1.20.1

geckolib_version=4.8.4

dev_recipe_viewer=both

cardinal_components_version=5.2.2
cloth_config_version=11.1.118
patchouli_version=84
paucal_version=0.6.0-pre-118
inline_version=1.2.2
serialization_hooks_version=0.4.99999

photon_modrinth_version=mc1.20.1-1.1.17-fabric

accessories_modrinth_version=1.0.0-beta.47+1.20.1

hexdebug_modrinth_version=0.8.0+1.20.1
ioticblocks_modrinth_version=SJMDeeZs
architectury_modrinth_version=9.2.14+fabric
modmenu_version=7.2.2
