[build-system]
requires = [
    "hatchling",
    "hatch-gradle-version>=0.9.5",
]
build-backend = "hatchling.build"

[project]
name = "hexdoc-hexwright"
description = "hexdoc plugin for Hexwright web book docs."
authors = [
    { name = "withgallantry" },
]
readme = "doc/README.md"
keywords = ["hexdoc"]
requires-python = ">=3.11"
dynamic = ["version", "dependencies", "optional-dependencies"]

[project.urls]
Homepage = "https://withgallantry.github.io/HexWright/"
Source = "https://github.com/withgallantry/HexWright"

[tool.hatch.version]
scheme = "gradle"
source = "gradle-properties"
py-path = "doc/src/hexdoc_hexwright/__version__.py"
key = "mod_version"

[tool.hatch.metadata.hooks.gradle-properties]
dependencies = [
    "hexdoc~=1!0.1.0a24",
    { package = "hexdoc-minecraft", op = "~=", py-version = "1.0.dev", key = "minecraft_version" },
    "hexdoc-hexcasting~=0.11.3.1.0",
]

[tool.hatch.metadata.hooks.gradle-properties.optional-dependencies]
dev = [
    "ruff~=0.11.2",
]

[tool.hatch.build]
artifacts = [
    "/doc/src/hexdoc_hexwright/_export/generated",
    "/doc/src/hexdoc_hexwright/__gradle_version__.py",
]

[tool.hatch.build.targets.sdist]
only-include = [
    "doc/src/hexdoc_hexwright",
    "gradle.properties",
]

[tool.hatch.build.targets.wheel]
packages = [
    "doc/src/hexdoc_hexwright",
]

[project.entry-points.hexdoc]
hexwright = "hexdoc_hexwright._hooks:HexwrightPlugin"

[tool.pyright]
pythonVersion = "3.11"
pythonPlatform = "All"

include = [
    "doc/src",
]
extraPaths = [
    "doc/src",
]

typeCheckingMode = "basic"
